language: csharp
mono:
  - 3.10.0
solution: PackMule.sln
script:
  - xbuild /p:Configuration=Release PackMule.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./PackMule.Tests/bin/Release/PackMule.Tests.dll